embedding_dim: 2048
attack_module: model.embed_tokens
formatting_tokens:
  answer_prefix: "Answer: "
  answer_suffix: ""
  prompt_prefix: "Question: "
  prompt_suffix: "\n"
hf_name: locuslab/tofu_ft_phi-1.5
attn_implementation: eager
load_in_8bit: false
load_in_4bit: false
